FROM oven/bun AS build
WORKDIR /app

# environment variable

ARG NODE_ENV
ARG VITE_API_BASE_URL
ARG VITE_PUBLIC_PATH

ENV NODE_ENV=$NODE_ENV \
    VITE_API_BASE_URL=$VITE_API_BASE_URL \
    VITE_PUBLIC_PATH=$VITE_PUBLIC_PATH

# build
COPY . .
RUN bun install
RUN bun run frontend:build

FROM nginx:alpine AS deploy
WORKDIR /app
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/apps/frontend/dist /usr/share/nginx/html

EXPOSE 5173